## Debugging Tools
# Indications of problems:
# - message: generic notification produced by the message function
# - warning: sth. is wrong, but not necessarily fatal; generated by the warning function
# - error: fatal problem; produced by the stop function
# - condition: generic concept (message, warning and error are special types of conditions)
#              for indicating that sth. unexpected can occur; programmers can create their own conditions.

log(-1)

printmessage <- function(x) {
    if (x > 0)
        print("x is greater than zero")
    else
        print("x is less than or equal to zero")    
    # do not print the return value to the console
    invisible(x)
}
printmessage(1)
printmessage(NA)

## fix the NA error
printmessage2 <- function(x) {
    if (is.na(x))
        print("x is a missing value")
    else if (x > 0) 
        print("x is greater than zero")
    else 
        print("x is less than or equal to zero")
    invisible(x)
}
printmessage2(1)
printmessage2(NA)
